In [1]:
import numpy as np

In [4]:
arreglo = np.array([0, 1, 2, 3, 4, 5])

In [5]:
arreglo, type(arreglo)

(array([0, 1, 2, 3, 4, 5]), numpy.ndarray)

In [6]:
notas = [16, 17, 14, 17, 19, 15]
ar_notas = np.array(notas, dtype=float)

In [7]:
ar_notas, type(ar_notas[0])

(array([16., 17., 14., 17., 19., 15.]), numpy.float64)

In [8]:
ar_notas_todas = np.array(([0, 1, 2, 3, 4, 5], notas))
ar_notas_todas

array([[ 0,  1,  2,  3,  4,  5],
       [16, 17, 14, 17, 19, 15]])

In [9]:
print(ar_notas_todas.ndim)

2


In [10]:
ar_notas.shape

(6,)

In [11]:
ar_notas_todas.shape

(2, 6)

In [12]:
arr = np.zeros((2, 3), dtype=float)

In [13]:
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
type(np.ones((3, 4)))

numpy.ndarray

In [46]:
ar2 = np.ones((3, 4), dtype = float)

In [47]:
type(ar2)

numpy.ndarray

In [21]:
ar4 = np.eye((4), dtype = float) #.identity is the same

In [22]:
ar4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
ar6 = np.arange(1, 9, 0.1)

In [26]:
ar6

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9])

### Operaciones básicas con arrays

In [34]:
arr = np.arange(1, 9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
arr.shape = (2, 4)

In [36]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [37]:
arr + arr 

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [38]:
arr - arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [39]:
arr*2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [40]:
arr ** arr

array([[       1,        4,       27,      256],
       [    3125,    46656,   823543, 16777216]], dtype=int32)

In [41]:
arr/arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [42]:
arr*arr

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

## Álgebra lineal

In [51]:
a = np.array([1, 2, 3], float)
b = np.array([0, 1, 1], float) 

np.dot(a, b)

5.0

In [52]:
a = np.array([[5, 2], [4, 8]], float)
b = np.array([[2, 4], [5, 3]], float) 

In [54]:
a, b

(array([[5., 2.],
        [4., 8.]]),
 array([[2., 4.],
        [5., 3.]]))

In [55]:
np.dot(a, b)

array([[20., 26.],
       [48., 40.]])

In [59]:
a@b 

array([[20., 26.],
       [48., 40.]])

In [79]:
a = np.array([[0, 1, 4], [5, 2, 3], [1, 4, 8]], float)
b = np.array([2, 3, 5], float) 

In [80]:
print(a)

[[0. 1. 4.]
 [5. 2. 3.]
 [1. 4. 8.]]


In [81]:
np.dot(a, b)

array([23., 31., 54.])

In [82]:
a@b

array([23., 31., 54.])

In [83]:
c = print(np.matmul(a, b))
c

[23. 31. 54.]


In [84]:
#determinante con linalg
a = np.array([[8, 5], [3, 4]])
print(a, "\n________________")
print(f"El determinante de a es: {np.linalg.det(a)}")

[[8 5]
 [3 4]] 
________________
El determinante de a es: 17.0


In [87]:
#autovalores y autovectores
vals, vecs = np.linalg.eig(a)

print(vals, "\n______________")
print(vecs, "\n______________")

[10.35889894  1.64110106] 
______________
[[ 0.90440309 -0.61810602]
 [ 0.4266791   0.78609474]] 
______________


### Funciones universales

In [99]:
a= np.array([2, 4, 9], float)
a

array([2., 4., 9.])

In [101]:
np.sqrt(a)

array([1.41421356, 2.        , 3.        ])

In [102]:
np.exp(a)

array([7.38905610e+00, 5.45981500e+01, 8.10308393e+03])

In [105]:
np.sin(a)

array([ 0.90929743, -0.7568025 ,  0.41211849])

### Funciones Universales Binarias

In [106]:
arr = np.array([5, 36, 17, 18, 9])
arr2 = np.array([8, 24, 17, 19, 9])

In [107]:
np.add(arr, arr2)

array([13, 60, 34, 37, 18])

In [109]:
np.subtract(arr, arr2)

array([-3, 12,  0, -1,  0])

In [110]:
np.array_equal(arr, arr2)

False

In [112]:
np.fmax(arr, arr2)

array([ 8, 36, 17, 19,  9])

In [117]:
arr_flot = np.random.rand(4, 3)
arr_flot

array([[0.80094668, 0.38531403, 0.23369679],
       [0.25728102, 0.21914872, 0.51344337],
       [0.02315928, 0.22845496, 0.47353554],
       [0.20711037, 0.74165519, 0.53641492]])

In [140]:
arr_ent = np.random.randint(10, size=(2, 3))
arr_ent

array([[5, 4, 8],
       [4, 3, 3]])

In [135]:
arr6 = np.full((3, 3), 6)
arr6

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [133]:
arr = np.append(arr, [12, 13, 14, 51])
arr

array([ 5, 36, 17, 18,  9, 12, 13, 14, 51, 12, 13, 14, 51, 12, 13, 14, 51])

In [134]:
np.insert(arr, 2, [42, 45])

array([ 5, 36, 42, 45, 17, 18,  9, 12, 13, 14, 51, 12, 13, 14, 51, 12, 13,
       14, 51])

In [137]:
np.insert(arr6, [1, 2], [43])

array([ 6, 43,  6, 43,  6,  6,  6,  6,  6,  6,  6])

In [138]:
arr_ent

array([[2, 9, 3],
       [7, 7, 2]])

In [142]:
np.delete(arr_ent, 1, axis=0)

array([[5, 4, 8]])

## Transformaciones

In [156]:
arr_ent = np.random.randint(100, size=(3, 4))
arr_ent

array([[64, 47,  1, 63],
       [44, 66, 83, 32],
       [93, 11, 71, 42]])

In [145]:
arr_ent.astype(float)

array([[59.,  4., 85., 30.],
       [77., 34., 13., 70.],
       [82., 93., 15., 98.]])

In [146]:
arr_ent

array([[59,  4, 85, 30],
       [77, 34, 13, 70],
       [82, 93, 15, 98]])

In [158]:
arr_ent.sort()
arr_ent

array([[ 1, 47, 63, 64],
       [32, 44, 66, 83],
       [11, 42, 71, 93]])

In [159]:
arr_ent.sort(axis=0)
arr_ent

array([[ 1, 42, 63, 64],
       [11, 44, 66, 83],
       [32, 47, 71, 93]])

In [161]:
arr_ent = arr_ent.reshape(6, 2)
arr_ent

array([[ 1, 42],
       [63, 64],
       [11, 44],
       [66, 83],
       [32, 47],
       [71, 93]])

In [162]:
plano_arr = arr_ent.flatten()

print(arr_ent)
print(plano_arr)

[[ 1 42]
 [63 64]
 [11 44]
 [66 83]
 [32 47]
 [71 93]]
[ 1 42 63 64 11 44 66 83 32 47 71 93]


In [164]:
lista_arr = plano_arr.tolist()
lista_arr, type(lista_arr)

([1, 42, 63, 64, 11, 44, 66, 83, 32, 47, 71, 93], list)

In [166]:
arr_ent

array([[ 1, 42],
       [63, 64],
       [11, 44],
       [66, 83],
       [32, 47],
       [71, 93]])

In [167]:
arrays = np.split(arr_ent, 3)
arrays

[array([[ 1, 42],
        [63, 64]]),
 array([[11, 44],
        [66, 83]]),
 array([[32, 47],
        [71, 93]])]

In [172]:
np.shape(arrays)

(3, 2, 2)

In [168]:
np.concatenate((arrays[1], arrays[0]), axis = 1)

array([[11, 44,  1, 42],
       [66, 83, 63, 64]])

In [174]:
arr_ent = np.random.randint(100, size=(3, 4))
arr_ent

array([[65, 97, 62, 82],
       [30, 68, 72, 99],
       [63, 12, 97, 94]])

In [178]:
arr_entT = arr_ent.transpose()
arr_entT

array([[65, 30, 63],
       [97, 68, 12],
       [62, 72, 97],
       [82, 99, 94]])

## Indexación y slicing

In [179]:
a = np.array(range(64)).reshape((8, 8))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [181]:
a[1, 1]

9

In [184]:
a[0:7:2,]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [183]:
a[1, 3:]

array([11, 12, 13, 14, 15])

In [185]:
a[[1, 3, 5], [3, 6, 7]]

array([11, 30, 47])

In [186]:
a[[1, 3, 5], ::3]

array([[ 8, 11, 14],
       [24, 27, 30],
       [40, 43, 46]])

In [187]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [188]:
data = np.arange(8)
data

array([0, 1, 2, 3, 4, 5, 6, 7])

In [191]:
data < 4

array([ True,  True,  True,  True, False, False, False, False])

In [190]:
data[data<4]

array([0, 1, 2, 3])

In [192]:
data[np.array([ True,  True,  True,  True, False, False, False, False])]

array([0, 1, 2, 3])

In [193]:
amigos = np.array(['giulia', 'victor', 'johel', 'andreina'])

In [198]:
name_out = 'giulia'
name_out in amigos

True

In [199]:
amigos[amigos!=name_out]

array(['victor', 'johel', 'andreina'], dtype='<U8')